# Generated by Django 6.0.4 on 2026-04-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('furigana', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('high_school', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('graduation_university', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_year', models.IntegerField()),
                ('hospital', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('furigana', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年'), (5, '5年'), (6, '6年')])),
                ('birth_date', models.DateField()),
                ('hometown', models.CharField(choices=[('盛岡市', '盛岡市'), ('花巻市', '花巻市'), ('北上市', '北上市'), ('奥州市', '奥州市'), ('一関市', '一関市'), ('宮古市', '宮古市'), ('釜石市', '釜石市'), ('久慈市', '久慈市'), ('二戸市', '二戸市'), ('その他', 'その他')], max_length=100)),
                ('high_school', models.CharField(max_length=100)),
                ('high_school_graduation_year', models.IntegerField()),
                ('hobby', models.TextField()),
                ('desired_department', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
