# Generated by Django 6.0.4 on 2026-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_graduate_email_alter_graduate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
